language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - DEPENDENCIES="--prefer-lowest --prefer-stable"
  - DEPENDENCIES=""

before_script:
  - composer self-update
  - rm composer.lock
  - composer update --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: Check coding standards
      php: 7.3
      env: DEPENDENCIES="" PHP=""
      script: vendor/bin/phpcs

    - stage: Run static analysis check
      php: 7.3
      env: DEPENDENCIES="" PHP=""
      script: vendor/bin/psalm

notifications:
  on_success: never
  on_failure: always
